adds CUDA_HOME configure setting (defaults to /opt/cuda/5.0 currently)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,7 +273,7 @@ PACKAGE_BUGREPORT=''
 
 ac_subdirs_all="$ac_subdirs_all osprey/cygnus"
 ac_subdirs_all="$ac_subdirs_all osprey-gcc-4.2.0"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MACHINE_TYPE CROSS_TARGET BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_FFE_OPTIMIZE BUILD_LIB_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_GNU3 BUILD_FORTRAN WHIRL_HAS_ID_FIELD BUILD_SKIP_IPA BUILD_TYPE DRAGON_SUPPORT GCC_CONFIGURE_TARG GCC_DIR BUILD_GNU4 ENABLE_COARRAYS BUILD_CAF_RUNTIME GASNET_HOME ARMCI_HOME ARMCI_NETWORK_LIBS GASNET_CONDUITS DEFAULT_COMM BASH_PATH MPI_INCLUDE CAFRT_ENABLE_TRACES CAFRT_ENABLE_PROFILES DEFAULT_CAF_HEAP_SIZE BUILD_LIBUHINSTR TAU_ROOT TAU_LIBS EPIK_ROOT OPENUH_VERSION LIBLIST subdirs LIBOBJS LTLIBOBJS uh_config_arguments'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MACHINE_TYPE CROSS_TARGET BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_FFE_OPTIMIZE BUILD_LIB_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_GNU3 BUILD_FORTRAN WHIRL_HAS_ID_FIELD BUILD_SKIP_IPA BUILD_TYPE DRAGON_SUPPORT GCC_CONFIGURE_TARG GCC_DIR BUILD_GNU4 ENABLE_COARRAYS BUILD_CAF_RUNTIME GASNET_HOME ARMCI_HOME ARMCI_NETWORK_LIBS GASNET_CONDUITS DEFAULT_COMM BASH_PATH MPI_INCLUDE CAFRT_ENABLE_TRACES CAFRT_ENABLE_PROFILES DEFAULT_CAF_HEAP_SIZE BUILD_LIBUHINSTR TAU_ROOT TAU_LIBS EPIK_ROOT OPENUH_VERSION CUDA_HOME LIBLIST subdirs LIBOBJS LTLIBOBJS uh_config_arguments'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -823,6 +823,7 @@ Optional Packages:
                           fortran programs. Can use suffixes K,M,G for
                           kilobytes,megabytes,gigabytes respecitvely. Will be
                           30M if unspecified.
+  --with-cuda=<cuda path> CUDA path for building libopenacc
   --with-build-optimize=DEFAULT|DEBUG	Use DEFAULT or DEBUG flags in compiler build
   --with-build-ffe-optimize=DEFAULT|DEBUG Use DEFAULT or DEBUG flags in FFE build
   --with-build-lib-optimize=DEFAULT|DEBUG Use DEFAULT or DEBUG flags in library build.
@@ -1516,6 +1517,16 @@ else
   DEFAULT_CAF_HEAP_SIZE="30M"
 fi;
 
+# cuda
+
+# Check whether --with-cuda or --without-cuda was given.
+if test "${with_cuda+set}" = set; then
+  withval="$with_cuda"
+  CUDA_HOME="$with_cuda"
+else
+  CUDA_HOME="/opt/cuda/5.0"
+fi;
+
 # set bash path
 BASH_PATH=`which bash`
 
@@ -1614,6 +1625,14 @@ echo "$as_me: error: Specified --with-gasnet-root=<path> doesn't look right. Che
   if test  "${GASNET_CONDUITS}" = "*"; then
       { { echo "$as_me:$LINENO: error: Specified --with-gasnet-root=<path> doesn't look right. Check path." >&5
 echo "$as_me: error: Specified --with-gasnet-root=<path> doesn't look right. Check path." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+fi
+
+if test -n "${CUDA_HOME}"; then
+  if test ! -d "${CUDA_HOME}"; then
+      { { echo "$as_me:$LINENO: error: Specified --with-cuda=<path> doesn't look right. Check path." >&5
+echo "$as_me: error: Specified --with-cuda=<path> doesn't look right. Check path." >&2;}
    { (exit 1); exit 1; }; }
   fi
 fi
@@ -2123,6 +2142,7 @@ export GCC_CONFIGURE_TARG
 export GCC_CONFIGURE_CFLAGS
 
 # Variables to replace in the configurable files.
+
 
 
 
@@ -3091,6 +3111,7 @@ s,@TAU_ROOT@,$TAU_ROOT,;t t
 s,@TAU_LIBS@,$TAU_LIBS,;t t
 s,@EPIK_ROOT@,$EPIK_ROOT,;t t
 s,@OPENUH_VERSION@,$OPENUH_VERSION,;t t
+s,@CUDA_HOME@,$CUDA_HOME,;t t
 s,@LIBLIST@,$LIBLIST,;t t
 s,@subdirs@,$subdirs,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
